### ISSUE TITLE
用户 系统权限切换bug

### ISSUE THREAD

**Issue by gujiaming2022** [sbwml/TrollStore_zh_Hans#1]
切换为用户权限后，再切换系统权限无效

**Comment by qingtian110** [comment]
确实，翻译改多了，我给大佬提个 PR 修复下

**Comment by sbwml** [comment]
> 切换为用户权限后，再切换系统权限无效



> 确实，翻译改多了，我给大佬提个 PR 修复下

合了，下 https://github.com/sbwml/TrollStore_zh_Hans/releases/download/2.0.15/TrollStore.tar  试试
