### ISSUE TITLE
想自己构建TrollStore

### ISSUE THREAD

**Issue by guotaoeunke** [sbwml/TrollStore_zh_Hans#4]
请问如果我想自己构建TrollStore，需要怎么做。比如我想改改里面的界面 能做到吗？

**Comment by sbwml** [comment]
一定能，但我不会

从 Windows 版邮件发送

发件人: guotaoeunke
发送时间: 2024年7月24日 15:59
收件人: sbwml/TrollStore_zh_Hans
抄送: Subscribed
主题: [sbwml/TrollStore_zh_Hans] 想自己构建TrollStore (Issue #4)

请问如果我想自己构建TrollStore，需要怎么做。比如我想改改里面的界面 能做到吗？
