### ISSUE TITLE
171代码强制安装弹窗仍然是英文

### ISSUE THREAD

**Issue by gujiaming2022** [sbwml/TrollStore_zh_Hans#6]
Install Error 171
A non TrollStore or a Trollstore Lite app with the same identifier is already installed. If you are absolutely sure it is not, you can force install it.

**Comment by gujiaming2022** [comment]
> 这个弹窗如何复现

从AppStore下载原版YouTube，再用巨魔安装YouTube ipa，就会弹窗提醒强制覆盖安装。

**Comment by sbwml** [comment]
YouTube ipa 在哪下载

**Comment by sbwml** [comment]
https://github.com/sbwml/TrollStore_zh_Hans/releases/download/2.1/TrollStore.tar

重新安装下就有了
